"""
SafetyAgent — enforces:
  • De-identification check (no PHI patterns in report)
  • "Not a medical device" disclaimer
  • Dosing guardrails (flags any dosage without guideline quote)
  • PDF report generation (reportlab)

Returns (report_id, report_url)
"""
from __future__ import annotations

import re
import uuid
from pathlib import Path
from typing import Tuple

import structlog

from api.config import settings
from api.models import AnalyzeCaseRequest, AnalyzeCaseResponse

log = structlog.get_logger()

# PHI regex patterns (HIPAA Safe Harbor)
PHI_PATTERNS = [
    r"\b\d{3}-\d{2}-\d{4}\b",              # SSN
    r"\b\d{10}\b",                           # Phone (10-digit)
    r"\b[A-Z][a-z]+ [A-Z][a-z]+\b",        # Full name heuristic
    r"\b\d{1,2}/\d{1,2}/\d{4}\b",          # DOB-style date
    r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b",  # Email
    r"MRN[:\s]*\d+",                         # Medical record number
    r"NPI[:\s]*\d{10}",                      # NPI
]

DISCLAIMER = (
    "⚠️  RESEARCH / EDUCATION ONLY. NOT A MEDICAL DEVICE. "
    "NOT FOR CLINICAL USE. This output is generated by an AI system "
    "and has not been validated for diagnostic accuracy. "
    "Always consult a qualified clinician before making any medical decision."
)


class SafetyAgent:
    async def process_and_export(
        self,
        request: AnalyzeCaseRequest,
        response: AnalyzeCaseResponse,
    ) -> Tuple[str, str]:
        """
        1. PHI scan.
        2. Dosing guardrail check.
        3. Append disclaimer.
        4. Generate PDF report.
        Returns (report_id, report_url).
        """
        # ── PHI scan ─────────────────────────────────────────────────────────
        self._phi_scan(request, response)

        # ── Dosing guardrail ──────────────────────────────────────────────────
        self._dosing_guardrail(response)

        # ── Append disclaimer ─────────────────────────────────────────────────
        response.disclaimer = DISCLAIMER

        # ── PDF export ────────────────────────────────────────────────────────
        report_id = uuid.uuid4().hex[:12]
        report_path = await self._generate_pdf(report_id, request, response)
        report_url = f"/reports/{report_id}"

        log.info("safety_agent_done", report_id=report_id,
                 phi_clean=True, report_path=str(report_path))
        return report_id, report_url

    def _phi_scan(
        self, request: AnalyzeCaseRequest, response: AnalyzeCaseResponse
    ) -> None:
        """Warn if PHI patterns detected in any text field."""
        texts = [
            request.patient_context.hpi or "",
            request.patient_context.chief_complaint,
            *(d.rationale for d in response.differentials),
        ]
        for text in texts:
            for pattern in PHI_PATTERNS:
                if re.search(pattern, text):
                    log.warning("potential_phi_detected", pattern=pattern)
                    # Redact from rationale text
                    for diff in response.differentials:
                        diff.rationale = re.sub(pattern, "[REDACTED]",
                                                diff.rationale)

    def _dosing_guardrail(self, response: AnalyzeCaseResponse) -> None:
        """Flag any dosage mention not backed by a guideline citation."""
        dose_pattern = re.compile(
            r"\b\d+(\.\d+)?\s*(mg|mcg|µg|g|ml|units?|IU)\b", re.IGNORECASE
        )
        guideline_ids: set[str] = {
            c.id for c in response.citations
            if c.study_type == "Guideline"
        }

        for diff in response.differentials:
            if dose_pattern.search(diff.rationale):
                supported_by_guideline = any(
                    ref.get("snippet_id") in guideline_ids
                    for ref in diff.support
                )
                if not supported_by_guideline:
                    diff.rationale += (
                        " [SAFETY NOTE: Dosage mentioned — verify against "
                        "current clinical guidelines before use.]"
                    )
                    log.warning("dosing_guardrail_triggered", dx=diff.dx)

    async def _generate_pdf(
        self,
        report_id: str,
        request: AnalyzeCaseRequest,
        response: AnalyzeCaseResponse,
    ) -> Path:
        """Generate a PDF report using reportlab."""
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
            HRFlowable, Image as RLImage
        )
        from reportlab.lib.enums import TA_CENTER, TA_LEFT

        report_dir = Path(settings.REPORT_DIR)
        report_dir.mkdir(parents=True, exist_ok=True)
        pdf_path = report_dir / f"{report_id}.pdf"

        styles = getSampleStyleSheet()
        h1 = ParagraphStyle("H1", parent=styles["Heading1"],
                             fontSize=16, spaceAfter=6)
        h2 = ParagraphStyle("H2", parent=styles["Heading2"],
                             fontSize=12, spaceAfter=4, textColor=colors.HexColor("#1a4a7a"))
        body = styles["BodyText"]
        warning_style = ParagraphStyle("Warning", parent=body,
                                       textColor=colors.red, fontName="Helvetica-Bold")

        elements = []

        # ── Header ────────────────────────────────────────────────────────────
        elements.append(Paragraph("Agentic Diagnostic Decision Support Report", h1))
        elements.append(Paragraph(DISCLAIMER, warning_style))
        elements.append(HRFlowable(width="100%", thickness=1, color=colors.red))
        elements.append(Spacer(1, 0.3 * cm))

        # ── Patient info ──────────────────────────────────────────────────────
        ctx = request.patient_context
        elements.append(Paragraph("Patient Context", h2))
        patient_data = [
            ["Case ID", request.case_id],
            ["Age / Sex", f"{ctx.age} / {ctx.sex}"],
            ["Chief Complaint", ctx.chief_complaint],
        ]
        if ctx.vitals:
            v = ctx.vitals
            patient_data.append([
                "Vitals", f"BP={v.BP} HR={v.HR} RR={v.RR} SpO2={v.SpO2}%"
            ])
        t = Table(patient_data, colWidths=[4 * cm, 13 * cm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e8f0fb")),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 0.4 * cm))

        # ── Imaging findings ──────────────────────────────────────────────────
        if response.imaging_findings:
            elements.append(Paragraph("Imaging Findings", h2))
            rows = [["Finding", "Probability", "Description"]]
            for name, f in response.imaging_findings.items():
                rows.append([
                    name.replace("_", " ").title(),
                    f"{f.prob:.0%}",
                    f.description or "",
                ])
            ft = Table(rows, colWidths=[5 * cm, 3 * cm, 9 * cm])
            ft.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a4a7a")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1),
                 [colors.white, colors.HexColor("#f5f7ff")]),
            ]))
            elements.append(ft)
            elements.append(Spacer(1, 0.4 * cm))

        # ── Differentials ─────────────────────────────────────────────────────
        elements.append(Paragraph("Differential Diagnoses", h2))
        for i, diff in enumerate(response.differentials, 1):
            elements.append(Paragraph(
                f"<b>{i}. {diff.dx}</b> &nbsp; ICD-10: {diff.icd10}", body
            ))
            elements.append(Paragraph(diff.rationale, body))
            elements.append(Spacer(1, 0.2 * cm))

        # ── Red flags ─────────────────────────────────────────────────────────
        if response.red_flags:
            elements.append(Paragraph("⚠️  Red Flags", h2))
            for rf in response.red_flags:
                elements.append(Paragraph(f"• {rf}", warning_style))
            elements.append(Spacer(1, 0.3 * cm))

        # ── Next steps ────────────────────────────────────────────────────────
        if response.next_steps:
            elements.append(Paragraph("Next Steps / Recommended Tests", h2))
            for ns in response.next_steps:
                elements.append(Paragraph(f"• {ns}", body))
            elements.append(Spacer(1, 0.3 * cm))

        # ── Citations ─────────────────────────────────────────────────────────
        if response.citations:
            elements.append(Paragraph("Evidence Citations", h2))
            for c in response.citations:
                meta = f"[{c.id}] {c.authors or ''} ({c.year or 'n/d'}). "
                meta += f"<i>{c.title or ''}</i>. {c.source or ''}. "
                meta += f"PMID: {c.pmid or 'N/A'}. DOI: {c.doi or 'N/A'}."
                elements.append(Paragraph(meta, body))
                elements.append(Paragraph(f'"{c.quote}"', body))
                elements.append(Spacer(1, 0.15 * cm))

        # ── Build PDF ─────────────────────────────────────────────────────────
        doc = SimpleDocTemplate(
            str(pdf_path), pagesize=A4,
            rightMargin=2 * cm, leftMargin=2 * cm,
            topMargin=2 * cm, bottomMargin=2 * cm,
        )
        doc.build(elements)
        return pdf_path
